export const AllUserActionTypes = {
  GET_ALL_USERS: "GET_ALL_USERS",
  VIEW_USER_DETAIL: "VIEW_USER_DETAIL",
  DELETE_USER: "DELETE_USER",
  ADD_USER: "ADD_USER",
  UPDATE_USER: "UPDATE_USER",
  LOADING: "LOADING",
  ERROR: "ERROR",
};
